feat: remove mystery ACs in feature tests
vegaprotocol/vega pull request #10065
Opened 2023-11-13 17:29 UTC by Jiajia-Cui

closes #9994

2023-11-13 17:44 UTC, davidsiska-vega requested changes
I agree that other than the successor markets it can all go - let's have a look at the successor market.

2023-11-13 17:55 UTC, davidsiska-vega approved these changes, later dismissed

2023-11-22 13:45 UTC, ValentinTrinque submitted a review, later dismissed

2024-01-30 12:03 UTC, Sohill-Patel commented
- 0013-ACCT-022 replaced by 0013-ACCT-033
- 0003-MTMK-015 is still referenced in `palazzo` [0003-MTMK-015](https://github.com/vegaprotocol/specs/blob/palazzo/protocol/0003-MTMK-mark_to_market_settlement.md#0003-MTMK-015)

2024-01-30 15:44 UTC, Jiajia-Cui reviewed
LGTM

2024-01-31 11:09 UTC, davidsiska-vega approved these changes

2024-02-01 14:35 UTC, ValentinTrinque approved these changes

2024-02-01 14:36 UTC, merged