feat: add test for network profit and loss
vegaprotocol/vega pull request #10329
Opened 2024-01-05 14:14 UTC by cdummett

2024-01-05 17:28 UTC, EVODelavega approved these changes, later dismissed

2024-01-05 17:43 UTC, davidsiska-vega approved these changes

2024-01-05 17:44 UTC, davidsiska-vega requested changes
Let's add some AC codes as well so we've got all this in the bag.

2024-01-05 17:54 UTC, EVODelavega commented
> Let's add some AC codes as well so we've got all this in the bag.

Given that the spec doesn't state that the PnL for the network should be available (and that we're not providing that data), these specific tests arguably all fall under `0012-POSR-014`, or maybe `0012-POSR-009` as it's checking the network position over time, I guess

2024-01-05 18:02 UTC, davidsiska-vega approved these changes
🚀

2024-01-05 18:06 UTC, EVODelavega approved these changes

2024-01-08 12:41 UTC, ze97286 approved these changes

2024-01-08 12:55 UTC, merged