Add the vega nodewallet (eht/vega supported for now)
vegaprotocol/vega pull request #1496
Opened 2020-04-05 10:44 UTC by jeremyletang

Add the vega nodewallet (eht/vega supported for now)

- add a new command line: nodewallet, to import wallet for vega or other chains
- add new parameters for the init command (initialize the nodewallet with a passphrase and a dev wallet if needed)

closes #800 
closes #803

2020-04-06 10:42 UTC, EVODelavega reviewed
small comments

2020-04-09 08:49 UTC, ashleyvega reviewed
If we intend to open-source vega, I suggest we start being slightly more formal with comments (no more "we" or "let's") and mind spellings ("_instanciate_") and grammar ("_load all the wallet save in it_") a little more.

2020-04-14 10:11 UTC, EVODelavega approved these changes
LGTM

2020-04-14 12:03 UTC, edd requested changes

2020-04-15 10:37 UTC, merged