do not validate marketID and orderID by default in cancel order
vegaprotocol/vega pull request #2194
Opened 2020-09-04 08:40 UTC by jeremyletang

This PR remove the protobuf validation from the API, so we can specify 1 or more parameters instead of all mandatory.

2020-09-04 10:15 UTC, edd requested changes
One question that I don't understand, and I suspect the GraphQL schema needs an update to match the new validation (but I haven't checked)

2020-09-04 16:02 UTC, ponthief approved these changes
looks good already tested on branch

2020-09-08 09:21 UTC, edd approved these changes

2020-09-08 14:11 UTC, EVODelavega approved these changes
LGTM

2020-09-08 14:16 UTC, merged