Refactor price monitoring data structures
vegaprotocol/vega pull request #2528
Opened 2020-11-02 16:28 UTC by witgaw

Refactors DTOs used by price monitoring engine so that the triggers are a market parameter and update frequency is the network parameter. 
It also adds the network parameter containing default triggers which are to be used when no market parameter containing these is provided.

Closes #2504

2020-11-03 17:30 UTC, edd requested changes
This PR needs a description

2020-11-05 14:34 UTC, jeremyletang approved these changes

2020-11-10 14:22 UTC, edd reviewed
GraphQL still looks great

2020-11-10 14:22 UTC, edd approved these changes

2020-11-10 14:30 UTC, merged