Improvements to docs generated from proto files
vegaprotocol/vega pull request #2847
Opened 2021-01-20 12:55 UTC by cdm

Closes #2845 

* Add missing definitions, check pegged orders and liquidity provision info
* Clean up, removing full stops that was contentious last time a review was done on these comments. It looked like developers prefer without, so this makes it more unified.
* Docs reference perma URLS now include `docs.testnet.vega.xyz`

2021-01-20 12:57 UTC, jeremyletang approved these changes

2021-01-20 13:13 UTC, edd requested changes
Typos, pending..

2021-01-20 13:38 UTC, jeremyletang requested changes
Just unapproving so changes can be done if needed.

2021-01-20 15:05 UTC, candida-d requested changes
I've skimmed and highlighted some newly-added typos, existing errors (including some where the description doesn't match the field), and some previously existing typos

2021-01-25 15:32 UTC, candida-d approved these changes

2021-01-25 15:33 UTC, jeremyletang approved these changes

2021-01-25 15:33 UTC, merged