Updating liquidity module to use uint256 data type
vegaprotocol/vega pull request #3576
Opened 2021-06-09 12:11 UTC by peterbarrow

Updating any price variables to use the new uint256 data type.

2021-06-10 10:12 UTC, jeremyletang requested changes
Calculate Supllied stake will need to return num.Uint.
LiquidityProvision and LiquidityProvisionSubmission CommitmementAmount need to be changed  to num.Uint

2021-06-14 08:50 UTC, jeremyletang requested changes
CommitmentAmont in the LiquidityProvision and LiquidityProvisionSubmission needs to be changed to num.Uint.

2021-06-14 09:35 UTC, jeremyletang requested changes
Seeing that there's now a Decimal alias un the num package, let's change all import from  `github.com/shopspring/decimal` to `vegaprocol.io/vega/types/num` for the Decimal type

2021-06-16 10:05 UTC, EVODelavega approved these changes

2021-06-16 10:07 UTC, merged