Feature/collateral to uint256
vegaprotocol/vega pull request #3583
Opened 2021-06-10 08:05 UTC by cityhunteur

TODO

- [x] Fix `TestMarginUpdateOnOrder`
- [x] Fix `TestMTMLossSocialization`

2021-06-10 09:21 UTC, jeremyletang reviewed
OK, I started reviewing mostly the engine.go file.

A couple of comments:
- when returning an account or a balance we should clone the actual bigUint
- When passing a uint as parameter, eventually cloning too if needed.
- Also let's try to avoid unecessary allocation when possible for the equivalent of a += b.

2021-06-14 16:33 UTC, EVODelavega requested changes

2021-06-15 17:51 UTC, peterbarrow approved these changes

2021-06-15 18:24 UTC, EVODelavega approved these changes

2021-06-16 10:06 UTC, merged