Implemented market terminated state via the oracle trigger
vegaprotocol/vega pull request #3791
Opened 2021-07-20 12:26 UTC by ze97286

close #2790
 #3708
#2788

2021-07-21 07:50 UTC, jeremyletang reviewed
This sounds good to me.

@cdm @ashleyvega scripts for submitting markets for governance will need to be updated to keep working as now a second oracle_spec is required in the future product.

@ValentinTrinque @EVODelavega could you take a look at this PR too.

@vega-paul You may want to synchronise with @ze97286 as this PR will break all market proposal, therefore all system tests (bvt are not passing for now), but the change is minimal ultimaltely.

2021-07-21 10:08 UTC, peterbarrow submitted a review, later dismissed

2021-07-22 09:51 UTC, ValentinTrinque requested changes

2021-07-22 10:05 UTC, ValentinTrinque requested changes

2021-07-22 10:32 UTC, ValentinTrinque requested changes

2021-07-23 12:03 UTC, jeremyletang approved these changes

2021-07-23 12:04 UTC, merged