feature(broker) add capability to sent events to a socket stream
vegaprotocol/vega pull request #3795
Opened 2021-07-22 15:24 UTC by cityhunteur

This allows the Vega core to stream events to the DataNode, i.e. a remote broker.

TODOs
- [x] Improve logging
- [x] Graceful termination of routines

close #3819

2021-07-22 16:21 UTC, jeremyletang reviewed
just a first pass at the review.

2021-07-28 15:55 UTC, jeremyletang requested changes

2021-08-11 11:37 UTC, jeremyletang submitted a review, later dismissed
@EVODelavega @peterbarrow anymore comments on this one?

2021-08-11 11:47 UTC, peterbarrow submitted a review, later dismissed

2021-08-11 12:08 UTC, EVODelavega submitted a review, later dismissed

2021-08-11 12:19 UTC, karlem submitted a review, later dismissed

2021-08-11 12:32 UTC, karlem approved these changes

2021-08-11 12:32 UTC, merged