Markets snapshot
vegaprotocol/vega pull request #4190
Opened 2021-10-08 12:13 UTC by karlem

Close #4165

2021-10-27 10:17 UTC, EVODelavega requested changes

2021-11-01 16:44 UTC, EVODelavega submitted a review, later dismissed

2021-11-01 19:00 UTC, jeremyletang requested changes
OK, I went over most of it, a few comments, but boi, that's a lot of code.

One thing really, is that if we can move the snapshot specific code from the types out of them when possible (e.g EquityShare and ExpiringOrders).

2021-11-08 16:31 UTC, EVODelavega approved these changes

2021-11-08 16:59 UTC, jeremyletang approved these changes

2021-11-08 17:06 UTC, merged