added min validators net param + bug fix for overflow reward
vegaprotocol/vega pull request #4210
Opened 2021-10-12 10:18 UTC by ze97286

close #4206 #4220

2021-10-12 10:22 UTC, jeremyletang submitted a review, later dismissed

2021-10-13 13:01 UTC, jeremyletang requested changes
I might be wrong but I think there might be non-deterministic code in there. Commented in the piece of code.

2021-10-14 07:45 UTC, wwestgarth submitted a review, later dismissed

2021-10-14 18:26 UTC, jeremyletang approved these changes

2021-10-14 20:22 UTC, merged