Feature/time triggered oracle source for trading terminated
vegaprotocol/vega pull request #4595
Opened 2022-01-14 14:37 UTC by guoguojin

Closes #4478

2022-01-17 11:15 UTC, ValentinTrinque requested changes

2022-01-21 09:19 UTC, jeremyletang requested changes
Just requesting change to block the merge as I want to go through it before it's merged, and don't have the time just now.

2022-01-25 10:24 UTC, ValentinTrinque requested changes

2022-01-27 09:41 UTC, jeremyletang requested changes

2022-02-01 10:59 UTC, wwestgarth submitted a review, later dismissed

2022-02-01 11:45 UTC, ValentinTrinque requested changes

2022-02-01 11:50 UTC, ValentinTrinque requested changes

2022-02-01 11:53 UTC, ValentinTrinque requested changes

2022-02-01 16:40 UTC, ValentinTrinque requested changes

2022-02-01 17:25 UTC, ValentinTrinque approved these changes

2022-02-02 17:13 UTC, jeremyletang approved these changes
Looks good, might need a rebase though now.

2022-02-03 10:56 UTC, merged