feat: add scenario on bond-slashing specification 0044
vegaprotocol/vega pull request #5195
Opened 2022-04-06 15:22 UTC by Jiajia-Cui

2022-04-06 16:00 UTC, jeremyletang requested changes
this go mod looks wrong. can we run go mod tidy here.

2022-04-06 16:21 UTC, jeremyletang submitted a review, later dismissed

2022-04-07 10:21 UTC, jeremyletang submitted a review, later dismissed

2022-04-08 13:07 UTC, TomMcL submitted a review, later dismissed

2022-04-11 08:19 UTC, jeremyletang submitted a review, later dismissed

2022-04-11 08:59 UTC, jeremyletang approved these changes

2022-04-11 09:00 UTC, merged