Replace usage of `.IntoProto().String()` by custom stringer
vegaprotocol/vega pull request #5225
Opened 2022-04-12 17:48 UTC by ValentinTrinque

Close #5115

2022-04-14 19:54 UTC, EVODelavega submitted a review, later dismissed
At first glance, LGTM, but maybe wait for a second review before merging

2022-04-19 10:08 UTC, jeremyletang requested changes
A few .IntoProto().String() are left:
```
➜  vega git:(feature/5115-proto-string) ✗ grep -rn '.IntoProto().String()' .
./banking/snapshot.go:175:			e.log.Info("serialiseDeposits:", logging.Int("index", i), logging.String("ID", d.ID), logging.String("deposit", d.Deposit.IntoProto().String()))
./logging/fields.go:171:	return zap.String("order", o.IntoProto().String())
./logging/fields.go:190:	return zap.String(tag, o.IntoProto().String())
```

2022-04-29 08:08 UTC, wwestgarth submitted a review, later dismissed

2022-04-29 08:17 UTC, wwestgarth approved these changes

2022-04-29 08:32 UTC, jeremyletang approved these changes

2022-04-29 10:21 UTC, merged