Extend auction interaction feat test
vegaprotocol/vega pull request #5246
Opened 2022-04-19 10:52 UTC by witgaw

Extends and modifies the auction interaction feature test + implements functionality required to make it pass.

The main issue is that the auction trigger field in market data API doesn't always get modified to reflect the trigger that has extended the auction (https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0026-auctions.md#exiting-the-auction-mode).

This PR also brings implementation in line with spec changes, please see linked issues for details.

Blocked by: ~https://github.com/vegaprotocol/vega/issues/3570 https://github.com/vegaprotocol/vega/issues/3578~ ~https://github.com/vegaprotocol/vega/pull/5298~

Closes: https://github.com/vegaprotocol/vega/issues/3047 https://github.com/vegaprotocol/vega/issues/3570 https://github.com/vegaprotocol/vega/issues/4223 https://github.com/vegaprotocol/vega/issues/3362 https://github.com/vegaprotocol/vega/issues/5237

2022-04-19 15:42 UTC, EVODelavega requested changes
As pointed out in individual comments, and summarised on slack, I think we require some changes to the code still. The most important things I've noticed are:

* With the current implementation, I believe it's possible for someone to spam FOK/IOC orders at stupid prices to force a price auction to get triggered
* `ExtractOrders` can now return pointers to orders as they sit on the book, making it very easy to introduce bugs like: having an order at price level 1000, but reprice it to 2000 without updating the matching engine
* Possible changes to auction behaviours (comment on integration tests about that)
* Auction extensions effectively being treated as leaving 1 type of auction and starting a second auction immediately after (which as per spec should never happen)
* Snapshots may be broken
* If we have a horizon of, say 10s, and we get an indicative price/volume for the first time in the last seconds of the opening auction phase, the price bounds may be off, and we might trigger a panic when the opening auction ends. I think we should add an integration test that replicates this scenario to ensure this isn't the case

2022-04-27 11:46 UTC, witgaw reviewed
Addressed most of the comments

2022-05-20 12:56 UTC, EVODelavega submitted a review, later dismissed

2022-05-20 13:14 UTC, EVODelavega approved these changes

2022-05-20 13:40 UTC, merged