feat: LP undeployed with LP price at 0
vegaprotocol/vega pull request #6005
Opened 2022-08-26 14:46 UTC by Jiajia-Cui

Test LP probability of trading

2022-08-31 09:48 UTC, davidsiska-vega requested changes

2022-08-31 09:48 UTC, davidsiska-vega commented on core/integration/features/verified/LP-large-prob-trading-bug.feature
> +    # And the following assets are registered:
Can we get rid of the commented out part please?

2022-08-31 09:48 UTC, davidsiska-vega commented on core/integration/features/verified/LP-large-prob-trading-bug.feature
> +   Scenario: LP vol seems wrong when a new best bit/ask price comes in
What do we mean by this label? Seems wrong but is correct? I am assuming the test is passing if it's a PR.

2022-08-31 09:48 UTC, davidsiska-vega commented on core/integration/features/verified/LP-large-prob-trading-bug.feature
> +Feature: Replicate LP getting distressed during continuous trading, check if penalty is implemented correctly
I don't see any LP getting distressed or penalty applied.

2022-08-31 09:48 UTC, witgaw approved these changes, later dismissed
LGTM, just one very minor comment:

2022-08-31 09:48 UTC, witgaw commented on core/integration/features/verified/LP-large-prob-trading-bug.feature
> +    # target_stake = mark_price x max_oi x target_stake_scaling_factor x rf = 1000 x 10 x 1 x 0.1
Nitpick: comment is misleading if the mark price is 900 and open interest is 1 (rather than 1000 and 10).

2022-09-02 14:51 UTC, Jiajia-Cui commented
close this PR and create a new [PR](https://github.com/vegaprotocol/vega/pull/6007)

2022-09-02 14:51 UTC, closed without merging