Add field settlementPriceDecimals to GraphQL Future type
vegaprotocol/vega pull request #6021
Opened 2022-08-30 18:22 UTC by zale144

Closes #5694

2022-08-31 08:31 UTC, dexturr submitted a review, later dismissed

2022-08-31 09:07 UTC, wwestgarth approved these changes, later dismissed

2022-08-31 09:23 UTC, guoguojin commented
You also need to update the schema.graphql and add the settlementPriceDecimals field to the graphql message definition for Future otherwise you won't be able to request the field in a gql query.

2022-08-31 10:25 UTC, ValentinTrinque requested changes
As per @guoguojin comment.

2022-08-31 14:52 UTC, ValentinTrinque approved these changes

2022-09-01 10:11 UTC, dexturr approved these changes

2022-09-01 10:12 UTC, merged