feat: add a FT negative position desimal
vegaprotocol/vega pull request #6512
Opened 2022-10-14 14:48 UTC by Jiajia-Cui

2022-10-24 13:27 UTC, davidsiska-vega commented on core/integration/features/verified/0070-MKTD-market-decimal-places-negative.feature
> +    Scenario: 001, Markets with different precisions trade at the same price
Would it be worth checking the mark price; since that's somehow what the description implies?

2022-10-24 13:28 UTC, davidsiska-vega commented on core/integration/features/verified/0070-MKTD-market-decimal-places-negative.feature
> +    Scenario: 002, Users engage in a USD market auction, (0070-MKTD-003, 0070-MKTD-008)
> Users engage in a USD market auction 

What does this mean?

2022-10-24 13:31 UTC, davidsiska-vega commented on core/integration/features/verified/0070-MKTD-market-decimal-places-negative.feature
> +    Scenario: 002, Users engage in a USD market auction, (0070-MKTD-003, 0070-MKTD-008)
> 0070-MKTD-008 

Ditto for this one; "Trades prices, like orders, are shown in market precision." We'd need to see what's on the event bus / data node.

2022-10-24 13:31 UTC, davidsiska-vega commented on core/integration/features/verified/0070-MKTD-market-decimal-places-negative.feature
> +            | USD/DEC21 | USD        | ETH   | log-normal-risk-model-1 | default-margin-calculator | 1                | default-none  | price-monitoring-1 | default-usd-for-future | 5              |
Why keep all the positive decimal places markets given what the file name is?

2022-10-24 13:32 UTC, davidsiska-vega commented on core/integration/features/verified/0070-MKTD-market-decimal-places-negative.feature
> +Feature: Allow markets to be specified with a smaller number of decimal places than the underlying settlement asset
I don't understand why it's under `0070-MKTD-...` since we want to test negative PDPs specifically.

2022-10-25 15:44 UTC, davidsiska-vega submitted a review, later dismissed

2022-11-03 13:56 UTC, cdummett requested changes

2022-11-03 13:56 UTC, cdummett commented on core/integration/features/verified/Negative-Position-Decimal-Places.feature
> +Feature: Allow markets to be specified with a smaller number of decimal places than the underlying settlement asset
Not sure I understand how this description matches the scenarios? How do negative position decimal places relate to the underlying asset?

2022-11-03 13:56 UTC, cdummett commented on core/integration/features/verified/Negative-Position-Decimal-Places.feature
> +    Scenario: 002, test negative PDP when trading mode is continous (0003-MTMK-013, 0019-MCAL-010, 0029-FEES-014)
Spelling change: 
continous -> continuos

2022-11-03 14:03 UTC, cdummett approved these changes
LGTM

2022-11-03 14:33 UTC, merged