Fanout event source swallows errors
vegaprotocol/vega pull request #6740
Opened 2022-11-08 15:25 UTC by ettec

2022-11-08 17:24 UTC, pscott31 submitted a review, later dismissed

2022-11-09 11:01 UTC, zale144 submitted a review, later dismissed

2022-11-09 17:17 UTC, ettec commented on datanode/broker/buffered_event_source.go
> +			if !ok {
channel closure is not unexpected, jsut need to handle it

2022-11-09 17:18 UTC, ettec commented on datanode/broker/buffered_event_source.go
> +			if !ok {
same here, channel closure is not unexpected, just need to handle it - these things are chained so the upstream broker closing its channels is normal behaviour

2022-11-09 17:19 UTC, ettec commented on datanode/broker/buffered_event_source.go
> +	ctxWithCancel, cancelFunc := context.WithCancel(ctx)
the different context name is to differentiate the one passed into the read buffer from the one passed into write buffer.  The one passed into read buffer is cancelled when the write buffer exits.

2022-11-09 17:24 UTC, jeremyletang requested changes
Seems to be blocking for me locally, might need some more testing.

2022-11-09 18:31 UTC, ettec commented on datanode/broker/buffered_event_source.go
> +	ctxWithCancel, cancelFunc := context.WithCancel(ctx)
sorted the cancelFunc name

2022-11-10 11:34 UTC, zale144 commented
lgtm! 
@vegaprotocol/core 
Because the `broker.Receive` doesn't handle context cancel, and in order to prevent the `receiveCh` channel range from blocking, I would just consider adding this change to `broker.go`:

```
func (b *Broker) Receive(ctx context.Context) error {
	if err := b.eventSource.Listen(); err != nil {
		return err
	}

	receiveCh, errCh := b.eventSource.Receive(ctx)

	for {
		select {
		case <-ctx.Done():
			return nil
		case err := <-errCh:
			return err
		case e, ok := <-receiveCh:
			if !ok {
				return nil
			}
			if err := checkChainID(b.chainID, e.ChainID()); err != nil {
				return err
			}
			go b.Send(e)
		}
	}
}
```

Not sure if the `go b.Send(e)` is a good idea. Thoughts?

2022-11-10 18:13 UTC, jeremyletang approved these changes

2022-11-10 18:13 UTC, merged