feat: check impact from tau.scaling parameter
vegaprotocol/vega pull request #7448
Opened 2023-01-27 15:19 UTC by Jiajia-Cui

create an example in feature test as a guidance for system test 

link [issue](https://github.com/vegaprotocol/system-tests/issues/1094)

2023-01-27 15:45 UTC, davidsiska-vega commented on core/integration/features/verified/0034-PROB-liquidity_TauScaling.feature
> +    Given the following network parameters are set:
let's explicitly state the LP range and also somewhere print what the price monitoring bounds are or show where on the book the LP volume is actually landing

2023-01-27 17:41 UTC, davidsiska-vega requested changes

2023-01-27 17:41 UTC, davidsiska-vega commented on core/integration/features/verified/0034-PROB-liquidity_TauScaling.feature
> +      | market.liquidity.probabilityOfTrading.tau.scaling   | 10    |
On line 3 we say tau scaling is 1, is 10 what we want here? Because then the next scenario also looks like the scaling is 10.

2023-01-30 16:55 UTC, davidsiska-vega approved these changes

2023-02-16 11:09 UTC, jeremyletang approved these changes

2023-02-16 11:43 UTC, merged