fix: add block height to graphql schema for stake linking
vegaprotocol/vega pull request #7660
Opened 2023-02-22 16:31 UTC by pscott31

Closes #7413

2023-02-22 16:35 UTC, wwestgarth approved these changes, later dismissed

2023-02-22 16:47 UTC, candida-d requested changes, later dismissed
typo fix

2023-02-22 16:47 UTC, candida-d commented on datanode/gateway/graphql/schema.graphql
> +  "The (ethereum) block hight of the link/unlink"
```suggestion
  "The (ethereum) block height of the link/unlink"
```

2023-02-23 20:00 UTC, dexturr approved these changes

2023-02-23 20:09 UTC, jeremyletang approved these changes

2023-02-23 20:36 UTC, merged