feat: buffered events file reader
vegaprotocol/vega pull request #7662
Opened 2023-02-22 17:38 UTC by ettec

closes #7517 adds the reader for event buffer files and removes the legacy event file reader.  Consolidates all event files to conform with the buffer file format so we only have one format.

2023-02-22 17:47 UTC, ettec commented on core/broker/file_client.go
> +func WriteToBufferFile(bufferFile *os.File, bufferSeqNum uint64, event events.Event) error {
the file is used only for testing, this ensure we have one format across datanode and core

2023-02-22 17:48 UTC, EVODelavega requested changes, later dismissed
The core shouldn't produce event files. If we need them, we should dump the events the core emits by subscribing to the event stream/queue and persisting them there

2023-02-22 17:48 UTC, EVODelavega commented on core/broker/file_client.go
> +func WriteToBufferFile(bufferFile *os.File, bufferSeqNum uint64, event events.Event) error {
All the more reason the code shouldn't sit in the core

2023-02-22 17:55 UTC, pscott31 reviewed
Looks alright to me, though I'm curious as to what Elias' objection is about.

I think if it were me rather than having to specify a directory that only contains event files, I might have made it so it looks for some sort of next-numbered file or something e.g. `vega.evt.001` -> `vega.evt.002` but I'm not actually sure that is that much nicer and it's a rather minor thing anyway

2023-02-22 17:56 UTC, ettec commented
> The core shouldn't produce event files. If we need them, we should dump the events the core emits by subscribing to the event stream/queue and persisting them there



> The core shouldn't produce event files. If we need them, we should dump the events the core emits by subscribing to the event stream/queue and persisting them there

Summary of discussion just now->  view on balance on discussion with Phil is its better to keep this functionality in place in core in  case we encounter an issue such as has been encounted in the past where the event stream received by datanode was different to that being produced by core.  So the change here is to existing code  just to make the format consistent for event files, such that we only need one reader and don't have compatibility issues.

2023-02-22 17:56 UTC, pscott31 commented
> The core shouldn't produce event files. If we need them, we should dump the events the core emits by subscribing to the event stream/queue and persisting them there

But it already does, and it's massively helpful for debugging and developing (e.g. when the system tests run, they generate an event file that I can play directly through datanode to recreate what happened)

2023-02-23 14:18 UTC, pscott31 submitted a review, later dismissed

2023-02-23 18:58 UTC, pscott31 approved these changes

2023-02-23 19:01 UTC, merged