Feat/7840 make chunk time interval configurable
vegaprotocol/vega pull request #7842
Opened 2023-03-14 17:06 UTC by guoguojin

Closes #7840

2023-03-14 17:08 UTC, pscott31 approved these changes, later dismissed

2023-03-15 10:21 UTC, ettec requested changes

2023-03-15 11:30 UTC, guoguojin commented on datanode/sqlstore/config.go
> +	ChunkInterval        string `string:"chunk-interval" description:"the interval at which to create new chunks, e.g '1 day', '1 month', '1 year' etc."`
resolved with https://github.com/vegaprotocol/vega/pull/7842/commits/b825143facfa623835ad53ba256f9edf9232deee

2023-03-15 11:34 UTC, ettec approved these changes

2023-03-15 14:58 UTC, merged