fix: Candle notional value migration deadlock
vegaprotocol/vega pull request #8686
Opened 2023-07-04 21:51 UTC by zale144

Resolves #8666

2023-07-05 09:28 UTC, ettec requested changes

2023-07-05 09:28 UTC, ettec commented on datanode/sqlstore/migrations/0012_candles_add_notional.sql
>  SELECT add_continuous_aggregate_policy('trades_candle_1_minute', start_offset => INTERVAL '1 day', end_offset => INTERVAL '1 minute', schedule_interval => INTERVAL '1 minute');
For each view, before reenabling the continuous aggregate, I think the following call will achieve this, but test it as not 100%.

refresh_continuous_aggregate("viewname", null, null)

2023-07-05 14:45 UTC, ettec approved these changes, later dismissed

2023-07-06 14:05 UTC, jeremyletang approved these changes

2023-07-06 14:05 UTC, merged