integrate sla rebased
vegaprotocol/vega pull request #8949
Opened 2023-07-31 10:37 UTC by jeremyletang

Rebase branch of: https://github.com/vegaprotocol/vega/pull/8744

Files with failing scenarios

## Witold
https://github.com/vegaprotocol/vega/pull/9098

- [x] core/integration/features/liquidity-provision/liquidity_provision_simple_pdp.feature
- [x] core/integration/features/liquidity-provision/mid-price-issue-amend.feature
- [x] core/integration/features/liquidity-provision/lp-margin-account-transfer-when-bestorder-change.feature
- [x] core/integration/features/liquidity-provision/bug-5110.feature
- [x] core/integration/features/liquidity-provision/bug-5147.feature
- [x] core/integration/features/liquidity-provision/automatic-adjustment-to-order-offsets-and-volumes.feature
- [x] core/integration/features/liquidity-provision/verify-CcySiska.feature
- [x] core/integration/features/liquidity-provision/mid-price-issue.feature
- [x] core/integration/features/liquidity-provision/lp-margin-post-auction.feature
- [x] core/integration/features/liquidity-provision/verify-simple-shape-order-sizes.feature
- [x] core/integration/features/liquidity-provision/lp-distressed-closeout.feature
- [x] core/integration/features/liquidity-provision/lp-distressed-closeout-pdp.feature
- [x] core/integration/features/price_monitoring/price-monitoring-lognormal2.feature
- [x] core/integration/features/price_monitoring/3362-failing-system-tests-trigger-with-amend.feature
- [x] core/integration/features/price_monitoring/volume-near-price-mon-bounds.feature
- [x] core/integration/features/price_monitoring/3362-failing-system-tests.feature
- [x] core/integration/features/price_monitoring/volume-near-price-mon-bounds-2.feature
- [x] core/integration/features/auctions/opening-auction-uncross.feature
- [x] core/integration/features/auctions/opening-auction-price.feature
- [x] core/integration/features/auctions/liquidity-uncross.feature
- [x] core/integration/features/auctions/3528-indefinite-auction-extension.feature
- [x] core/integration/features/auctions/5460-market-order-cannot-trade-due-to-auction.feature
- [x] core/integration/features/auctions/enter-leave-liquidity-auction.feature
- [x] core/integration/features/orders/offsets_with_decimals.feature
- [x] core/integration/features/orders/FOK_order_stopped.feature
- [x] core/integration/features/margin/596-Opened-positions-traded-out-but-there-is-still-money-sitting-in-a-margin-account.feature
- [x] core/integration/features/margin/596-margin-account-non-zero-after-trading-out-market-order.feature
- [x] core/integration/features/margin/6202-release-excess-on-amend.feature
- [x] core/integration/features/margin/635-margin-calculation.feature
- [x] core/integration/features/margin/614-margin-calculations-fixes.feature
- [x] core/integration/features/margin/verified_margins_case1-decimal-places.feature
- [x] core/integration/features/closeouts/1919-close-out-occurs-above-maintenance.feature
- [x] core/integration/features/closeouts/1847-closeout-short.feature
- [x] core/integration/features/closeouts/1847-closeout-long.feature
- [x] core/integration/features/closeouts/2878-close-out-orders-allowed-when-under-initial.feature
- [x] core/integration/features/closeouts/1847-closeout-short-with-fees.feature
- [x] core/integration/features/closeouts/position-resolution-after-auction.feature
- [x] core/integration/features/closeouts/1847-closeout-long-with-fees.feature
- [x] core/integration/features/accounts/2943-distressed-trader-has-general-balance.feature
- [x] core/integration/features/verified/0038-OLIQ-verified-complex-shape-order-sizes.feature
- [x] core/integration/features/verified/0081-SUCM-multiple_successor_markets.feature
- [x] core/integration/features/verified/liquidity-provision-bond-account.feature
- [x] core/integration/features/verified/0042-LIQF-fees_rewards.feature
- [x] core/integration/features/verified/Issue-6004-ProbOfTrading_Refactoring.feature
- [x] core/integration/features/verified/0003-MTMK-mark_to_market_settlement.feature
- [x] core/integration/features/verified/0006-POSI-AC-008.feature
- [x] core/integration/features/verified/closeout-lognormal.feature

## Charlie
- [x] core/integration/features/position_tracking/verified-positions-resolution-5-lognormal.feature
- [x] core/integration/features/position_tracking/verified-positions-resolution-5-lognormal_pdp.feature
- [x] core/integration/features/settlement/settlement_at_expiry_by_time_from_internal_oracle.feature
- [x] core/integration/features/fees/trading-fees-pdp.feature
- [x] core/integration/features/fees/setting-fee-and-rewarding-lps.feature
- [x] core/integration/features/verified/0042-LIQF-fees_rewards_growing_market.feature

## Jiajia
- [x] core/integration/features/successor-markets-simple.feature
- [x] core/integration/features/successor-markets-ELS.feature
- [x] core/integration/features/successor-markets-expiration.feature
- [x] core/integration/features/verified/0032-PRIM-price_monitoring_lognormal.feature
- [x] core/integration/features/verified/0015-INSR-insurance_pool_balance_test.feature
- [x] core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case3.feature
- [x] core/integration/features/verified/0042-LIQF-fees_rewards_VirtualStake.feature
- [x] core/integration/features/verified/closeout-LP_New_Exit_Price.feature
- [x] core/integration/features/verified/0042-LIQF-fees_rewards_multi_lps.feature
- [x] core/integration/features/verified/Slippage-Calc-in-Margin-Level.feature
- [x] core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case2.feature
- [x] core/integration/features/verified/0011-MARA-016017.feature
- [x] core/integration/features/verified/0002-STTL-settlement_at_expiry.feature
- [x] core/integration/features/verified/0029-FEES-fees.feature
- [x] core/integration/features/verified/0070-MKTD-market-decimal-places.feature
- [x] core/integration/features/verified/0042-LIQF-fees_rewards_large_distribution_time.feature
- [x] core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case1.feature
- [x] core/integration/features/verified/Funding-treasury.feature
- [x] core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case6.feature
- [x] core/integration/features/verified/0003-MTMK-mark_to_market_settlement_using_insurance_pool.feature
- [x] core/integration/features/verified/closeout-cascade.feature
- [x] core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case4.feature
- [x] core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case5.feature
- [x] core/integration/features/verified/0038-OLIQ-liquidity_provision_creation.feature
- [x] core/integration/features/verified/0019-MCAL-margin_calculator-risk_parameters.feature
- [x] core/integration/features/verified/0011-MARA-006.feature
- [x] core/integration/features/verified/0029-FEES-trading_fees.feature
- [x] core/integration/features/verified/risk-parameters-sigma-test.feature
- [x] core/integration/features/settlement/mark_to_market_interval_positions.feature
- [x] core/integration/features/settlement/mark_to_market_settlement_pdp.feature
- [x] core/integration/features/fees/amend-fees.feature
- [x] core/integration/features/rewards/multi_asset_multi_market_fees_rewards.feature (bug, Jeremy is working on a fix)
- [x] core/integration/features/rewards/asset_fees_rewards.feature
- [x] core/integration/features/verified/risk-parameters-ranges-test.feature
- [x] core/integration/features/verified/0034-PROB-liquidity_TauScaling.feature
 - [x] core/integration/features/verified/Negative-Position-Decimal-Places.feature
- [x] core/integration/features/verified/Margin-Levels.feature

## Valentin

- [x] core/integration/features/verified/Test-PnL.feature

## Karel
- [x] core/integration/features/verified/liquidity-provision-bond-account-dp.feature
- [x] core/integration/features/verified/Funding-insurance_pool.feature
- [x] core/integration/features/verified/0034-PROB-liquidity_measure.feature
- [x] core/integration/features/verif [...]

2023-08-16 09:42 UTC, jeremyletang commented
```
{
"system-tests": "sla-future-market-proposal"
}
```

2023-08-18 16:38 UTC, candida-d requested changes

2023-08-18 16:38 UTC, candida-d commented on datanode/gateway/graphql/schema.graphql
> -
This shouldn't be removed so that it can still be compatible rather than a breaking change.

2023-08-18 16:38 UTC, candida-d commented on datanode/gateway/graphql/schema.graphql
> -  lpPriceRange: String!
This shouldn't be removed so that it can still be compatible rather than a breaking change.

2023-08-23 15:12 UTC, merged