refactor: include funding payment in liq. price
vegaprotocol/vega pull request #9467
Opened 2023-09-19 10:15 UTC by witgaw

+ additional tests for consistency

2023-09-20 14:29 UTC, candida-d requested changes

2023-09-20 14:29 UTC, candida-d commented on protos/sources/data-node/api/v2/trading_data.proto
> +  // Collateral available needs to be provided scaled to asset decimal places. Liquidation price returned scaled to asset decimal places by default.
```suggestion
  // Collateral available needs to be provided scaled to asset decimal places. Liquidation price returned is scaled to asset decimal places by default.
```

2023-09-20 14:29 UTC, candida-d commented on protos/sources/data-node/api/v2/trading_data.proto
> +  // Optional argument specifying if the liqudiation price estimates should be scaled to market decimal places (scaled to asset decimal places by default).
```suggestion
  // Argument specifying if the liquidation price estimates should be scaled to market decimal places, by default they are scaled to asset decimal places.
```

2023-09-20 14:29 UTC, candida-d commented on protos/sources/data-node/api/v2/trading_data.proto
> +  // Liquidation price estimates are scaled to asset decimal places by default, unless a flag to scale to market decimal places is specified in the request.
```suggestion
  // Liquidation price estimates are scaled to asset decimal places by default, unless an argument to scale to market decimal places is specified in the request.
```

2023-09-20 14:31 UTC, candida-d commented on protos/sources/data-node/api/v2/trading_data.proto
> +  optional bool scale_liquidation_to_market_decimals = 5;
Should this also be added to GraphQL?

2023-09-20 14:39 UTC, jeremyletang reviewed
Could you had the changes to the graphql API as well please?

2023-09-20 14:47 UTC, witgaw commented on protos/sources/data-node/api/v2/trading_data.proto
> +  optional bool scale_liquidation_to_market_decimals = 5;
Yep, added now, thanks

2023-09-20 14:50 UTC, candida-d submitted a review, later dismissed

2023-09-21 11:01 UTC, jeremyletang approved these changes

2023-09-21 11:01 UTC, merged