feat: cache and forward referral rewards multiplier and factor multplier
vegaprotocol/vega pull request #9687
Opened 2023-10-06 12:45 UTC by ettec

closes #9678

2023-10-06 16:22 UTC, ValentinTrinque requested changes

2023-10-09 11:00 UTC, candida-d commented on protos/sources/data-node/api/v2/trading_data.proto
> +  // Rewards factor multiplier for the party.
Could you go into more detail about what the difference is between these two?

2023-10-09 12:58 UTC, jeremyletang commented
@ettec could you fix the commit message and address @candida-d's comment please?

2023-10-09 13:28 UTC, ValentinTrinque approved these changes, later dismissed

2023-10-09 14:30 UTC, jeremyletang approved these changes

2023-10-09 14:57 UTC, merged